#!/usr/bin/perl

use strict;
use warnings;

open IN, "<", "ShephongParserTest.java";
open OUT, ">", "ShephongToStringWalkerTest.java";

my $line;

while (($line = <IN>) !~ /^import/) {
  print OUT $line;
}
print OUT "import de.luh.psue.cklab.shephong.backend.ToStringWalker;\n";
print OUT $line;

while (($line = <IN>) !~ /^public class/) {
  $line =~ s/\(kiki\)/(none, autogenerated)/;
  print OUT $line;
}
print OUT <<'HERE';
public class ShephongToStringWalkerTest extends TestCase {
	/**
	 * Call assertParsable from here, discarding the given argument
	 * and change it to a ToStringWalker instance.
	 *
	 * This whole file is automatically generated by a perl-script.
	 */
	@SuppressWarnings("unchecked")
	public void assertParsableWrapper (Class parserClass, String input, String expectedResult) throws CompilerException {
		assertParsable (parserClass, input, new ToStringWalker ());
	}

HERE

while ($line = <IN>) {
  $line =~ s/assertParsable/assertParsableWrapper/g;
  print OUT $line;
}

